# Generated by Django 4.2 on 2026-03-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=200)),
                ('client_telephone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('nombre_personnes', models.IntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('demandes_speciales', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='commandes.table')),
            ],
            options={
                'ordering': ['date', 'heure'],
                'unique_together': {('table', 'date', 'heure')},
            },
        ),
    ]
